import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  robots: {
    index: true,
    follow: true,
    nocache: true,
    googleBot: {
      index: true,
      follow: false,
      noimageindex: true,
      'max-video-preview': -1,
      'max-image-preview': 'large',
      'max-snippet': -1,
    },
  },
}

export default function RootLayout({ children }) {
  return (
  	<html lang="en">
      <body className={inter.className}>
				<header>
					<p>Travel Partner</p>
					<img src="" alt="" />
				</header>
				{children}
				<footer>
				<div>
				<ul>
					<li>
						<a href="">О нас</a>
					</li>
					<li>
						<a href="">О сервисе</a>
					</li>
					<li>
						<a href="">Политика конфиденциальности</a>
					</li>
					<li>
						<a href="">Поддержка</a>
					</li>
				</ul>
				<p>© 2023, Travel Partner — ваш помощник в путешествии</p>
				</div>
			</footer>
			</body>
    </html>
  )
}
